
import { Inter } from "next/font/google";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import Head from 'next/head';
import {
  ClerkProvider
} from '@clerk/nextjs';
import Provider from "./Provider";
import './globals.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Project HUB",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <Head>
          <title>{metadata.title}</title>
          <link rel="icon" href="app\favicon.ico" sizes="any" />
    <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-7055031129192732"
     crossorigin="anonymous"></script>
          </Head>
        <body className={inter.className}>
          <Provider>{children}</Provider>
          <ToastContainer />
        </body>
      </html>
    </ClerkProvider>
  );
}
